-- QUE TENHA O TERMO 
EXEC sp_ForEachDB '
  SELECT DB_NAME(), *
  FROM INFORMATION_SCHEMA.ROUTINES 
  WHERE ROUTINE_DEFINITION LIKE ''%ratear%''
  ORDER BY ROUTINE_NAME'
  
/*  
-- PELO NOME ESPECÍFICO 
EXEC sp_ForEachDB 
 'SELECT DB_NAME(), *
  FROM INFORMATION_SCHEMA.ROUTINES 
  WHERE SPECIFIC_NAME LIKE ''%ratear%''
  ORDER BY ROUTINE_NAME'  
*/  